#Type conversion function converse the data in the form of required format in the data is possible to convert..
a=input("enter int value")
print(type(a))
b=int(a)
print(type(b))
c=input("enter float value")
print(type(c))
d=float(c)
print(type(d))
i=input("enter complex value")
print(type(i))
j=complex(i)
print(type(j))
p=input("enter bool value")
print(type(p))
q=bool(p)
print(type(q))
